### ISSUE TITLE
Website para seguir a evolução

### ISSUE THREAD

**Issue by andrepcg** [avataranedotas/get_mobie#1]
Faz agora 1 ano que comecei a coleccionar os dados da Mobi.e. Na semana passada decidi construir um pequeno serviço para deixar a informação pública e após pesquisar um pouco na net descobri o teu trabalho devido a este tópico: https://www.clubeletricos.com/viewtopic.php?f=29&t=8236

https://carregadores.top

Como não tenho outra maneira de te contactar, escrevo aqui este issue apenas para te informar, podes achar interessante.

Cumprimentos!

**Comment by avataranedotas** [comment]
Olá.
Obrigado pelo contacto.

É interessante sim!
